config/routes.rb
Rails.application.routes.draw do
devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}
 
 root to: 'tests#index'

  resources :user_badges
  get 'user_badges', to: 'user_badges#index'
  resources :tests, only: :index do
    resources :questions, shallow: true do 
      resources :answers, shallow: true
    end
    member do
      post :start 
    end
  end

  resources :test_passages, only: %i[show update] do  
    member do 
      get :result
      post :gist
    end
  end
namespace :admin do 
  resources :badges
  resources :gists
  resources :tests do
    patch :update_inline, on: :member
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
end
end

app/models/badge.rb
class Badge < ApplicationRecord
	has_many :user_badges
	has_many :users, through: :user_badges

	  BADGE_RULES = {
      'Passing all tests in a category' => :category_completed?,
      'Passing the test successfully on the first try' => :success_first_try?,
      'Passing all tests of a certain level' => :level_complete?
  }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
	before_action :set_badges, only: %i[index]
	before_action :find_badge, only: %i[show edit update destroy]
	
	def index
	end

	def new
		@badge = Badge.new
	end

	def create
		@badge = Badge.new(badge_params)

	    if @badge.save
	      redirect_to action: :index
	    else
	      render :new
	    end
	end

	def show

	end

	def edit

	end

	def update

		if @badge.update(badge_params)
			redirect_to admin_badge_path @badge
		else
			render :edit
		end
	end

	def destroy
		@badge.destroy
		redirect_to admin_badges_path
	end

	private

	def badge_params
		params.require(:badge).permit(:title, :img, :rule)
	end

	def set_badges
	    @badges = Badge.all
	end

	def find_badge
		@badge = Badge.find(params[:id])
	end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
	before_action :set_badges, only: %i[index]

	def index
	end

	private

	def set_badges
	    @badges = Badge.all
	end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title, id: :badge_title %>
  </p><br>
    <p>
    <%= form.label :rule %>
    <%= form.text_field :rule, id: :badge_rule %>
  </p><br>
    <p>
    <%= form.label :img %>
    <%= form.text_field :img, id: :badge_img %>
  </p><br>
  
  
  
  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to "Back", admin_badges_path %>

app/views/admin/badges/index.html.erb
<div class="test-logo text-center mt-5">
<h1>Badges</h1>
</div>




<div class="row">
	<div class="container col-12 col-md-6">
		
		<p>
	<%= link_to "Create" , new_admin_badge_path, class: "btn btn-primary form-control" %>
</p>
		
	 <% @badges.each do |badge| %>
    <div>
    	<div class="form-group">
		<div class="form-control bg-light"> 
      <h3><%= badge.title %></h3>
     <%= image_tag(badge.img, width: 50, height: 50) %>
      <b><%= badge.rule %></b>
      <br>
      <%= link_to "Show", admin_badge_path(badge) %>
      <%= link_to "Edit", edit_admin_badge_path(badge) %>
		<td><%= button_to 'Delete',
           				 admin_badge_path(badge),
           				 class: "btn btn-danger",
           				 method: :delete,
           				 data:   { confirm: 'Are you sure?' } %>
    </div>
	</div>
	<br>
	</div>
  <% end %>

</div>

app/views/admin/badges/new.html.erb
<h1 class="text-center mt-5">Create</h1>

<%= render 'form' %>

<%= link_to "back", admin_badges_path %>

app/views/admin/badges/show.html.erb
<center>
  <p><h1>
    <%= @badge.title %> Badge
  </h1>
  </p>
</center>
  <div class="container col-12 col-md-4 mt-5">
<div class="form-group">
<div class="form-control bg-light"> 
<p>
  <strong>Rule:</strong>
  <%= @badge.rule %>
</p>
<p>
  <strong>Img:</strong>
  <%= image_tag(@badge.img, width: 50, height: 50) %>
</p>
</div>
</div>
  <%= link_to "Edit", edit_admin_badge_path(@badge) %>
  <%= link_to "Back", admin_badges_path %>