config/routes.rb
Rails.application.routes.draw do
devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}
 
 root to: 'tests#index'

  resources :user_badges
  get 'user_badges', to: 'user_badges#index'
  resources :tests, only: :index do
    resources :questions, shallow: true do 
      resources :answers, shallow: true
    end
    member do
      post :start 
    end
  end

  resources :test_passages, only: %i[show update] do  
    member do 
      get :result
      post :gist
    end
  end
namespace :admin do 
  resources :badges
  resources :gists
  resources :tests do
    patch :update_inline, on: :member
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
end
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :test
	has_many   :answers, dependent: :destroy
	validates  :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def current_question_number
    if next_question || current_question
      test.questions.order(:id).where('id < ?', current_question).count + 1
    else
      test.questions.count
    end
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)
    self.success_passed = true if success?
    save!
  end

  def success?
    score >= 85
  end

  def progress_percent
    ((current_question_number.to_f - 1) / total_questions * 100).round
  end

   def total_questions
    test.questions.size
  end

  def score
    (correct_question.to_f * 100 / test.questions.count).round
  end

  def completed?
    current_question.nil?
  end

  def time_up?
    time_left.negative?
  end

  def time_left
    test.time_in_sec - (Time.current - created_at)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort unless answer_ids.nil?
  end

  def correct_answers
    current_question.answers.where(correct: true)
  end

def next_question
     test.questions.order(:id).where('id > ?', current_question.id).first
end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

	before_action :authenticate_user!
	before_action :set_test_passage, only: %i[show update gist result]

	def show

	end

	def result

	end

	def update
	  @test_passage.accept!(params[:answer_ids])
	  if @test_passage.completed? || @test_passage.time_up?
	    TestsMailer.completed_test(@test_passage).deliver_now

	    if @test_passage.success_passed == true
	      badge = BadgesService.new(@test_passage)
	      badge.call
	      flash.now[:notice] = "Achievement received"
	    end

	    redirect_to result_test_passage_path(@test_passage)
	  else
	    render :show
	  end
	end
	
  def gist
    gist = GistQuestionService.new(@test_passage.current_question)
    gist.call
    if gist.success?
      gist_url = gist.url_hash
      @gist = Gist.create(user_id: @test_passage.user_id, question_id: @test_passage.current_question.id, gist_url: gist_url)
      flash.now[:notice] = t('.success', gist: helpers.link_to_gist(@gist)).html_safe
    else
      flash.now[:notice] = t('.failure')
    end
     redirect_to @test_passage
  end

	private

	def set_test_passage
		@test_passage = TestPassage.find(params[:id])
	end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/_progress_bar.html.erb
<%= content_tag :div, class: "progress mr-2 ml-2", data: { percent: @test_passage.progress_percent } do %>
  <div class="progress-bar" role="progressbar"
       aria-valuemin="0" aria-valuemax="100"><b><%= test_passage.progress_percent %>%</b></div>
<% end %><p>

app/views/test_passages/result.html.erb
<h1 class="text-center mt-5"><%= t('.header', title: @test_passage.test.title) %> </h1>
  <%= render 'test_passages/progress_bar', test_passage: @test_passage%>
<div class="container col-12 col-md-4 mt-5">
<div class="form-group">
<div class="form-control bg-light"> 
<% if @test_passage.success? %>
	<div>
		<strong class="text-success">
	Test was passed!</strong></p>
<% else %>
	<div>
		<strong class="text-danger">
	Test wasn't passed :( Please try again
</strong>
</div>
<% end %>
	<p>
		<strong>
		You scored <%= @test_passage.score %>
	</strong>
	</p>

</div>
</div>

  <h5><strong>
    Score: <%= @test_passage.score %> %
  </strong></h5>

<%= link_to 'All tests', tests_path, class: "btn btn-primary form-control" %>
</div>

app/views/test_passages/show.html.erb
<h1 class="text-center mt-5 mb-2">Passing The <%= @test_passage.test.title %> Test</h1>


<div class="container col-12 col-md-6">
<div class="form-group">
	<h3 class="mb-4">

	<%= render 'progress_bar', test_passage: @test_passage%>

</h3>
</div
>
	<% if @test_passage.test.time.present? %>
  <%= content_tag :div, class: 'timer col-12 col-md-6', data:{time_left: @test_passage.time_left} do %>
    <h3 class='time'></h3>
  <% end %>
  <% end %>

<div class="form-group">
<h1> <%= @test_passage.current_question.body %></h1>

<%= form_with url: test_passage_path(@test_passage), class: "form-control bg-light", local: true, method: :put do |form| %>
<%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
<div class="form-check form-switch">
<p>
	<%= b.check_box id: "answer_ids#{b.object.id}", class: "form-check-input" %>
	<%= b.label class: "form-check-label" %>
</p>
</div>
	<% end %>
</div>

	<div class="form-group">
	
	<p><%= form.submit 'Next', class: "btn btn-success form-control" %></p>
	</div>
	<div class="form-group">
		
		<p>
	<strong>Current question:</strong> <%= @test_passage.current_question_number %>
		</p>
		<p>
	<strong>Total questions:</strong> <%= @test_passage.test.questions.count %>
		</p>
	</div>
<% end %>
	<p>
			<%= button_to 'Gist Question' ,
            			 gist_test_passage_path(@test_passage),
            			  class: "btn btn-primary",
            			 method: :post %>
		</p>
</div>