config/routes.rb
Rails.application.routes.draw do
devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}
 
 root to: 'tests#index'

  resources :user_badges
  get 'user_badges', to: 'user_badges#index'
  resources :tests, only: :index do
    resources :questions, shallow: true do 
      resources :answers, shallow: true
    end
    member do
      post :start 
    end
  end

  resources :test_passages, only: %i[show update] do  
    member do 
      get :result
      post :gist
    end
  end
namespace :admin do 
  resources :badges
  resources :gists
  resources :tests do
    patch :update_inline, on: :member
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	scope      :correct_answ, -> { where(correct: true)}
	# validate   :validate_number_of_answers

	# private

	# def validate_number_of_answers
	#   errors.add(:title, "Question can have 1 to 4 answers") unless question.answers.count.between?(1, 4)
	# end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
	has_many :user_badges
	has_many :users, through: :user_badges

	  BADGE_RULES = {
      'Passing all tests in a category' => :category_completed?,
      'Passing the test successfully on the first try' => :success_first_try?,
      'Passing all tests of a certain level' => :level_complete?
  }
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tests, dependent: :destroy
end

app/models/gist.rb
class Gist < ApplicationRecord
	belongs_to :question
  	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :test
	has_many   :answers, dependent: :destroy
	validates  :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :category
	belongs_to :author, class_name: "User", foreign_key: :user_id, optional: true

	has_many   :test_passages
	has_many   :users, through: :test_passages
	has_many   :questions, dependent: :destroy


	validates  :title, presence:   true,
					  uniqueness: {scope: :level}

	validates  :level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

	default_scope -> { joins(:category).order(title: :asc) }

	scope      :easy, -> { where(level: 0..1).order(created_at: :desc) }
	scope      :medium, -> { where(level: 2..4).order(created_at: :desc) }
	scope      :hard, -> { where("level >= ?", 5).order(created_at: :desc) }

  def self.by_category(category)
    by_category(title_name).order(title: :desc).pluck(:title)
  end

  def test_to_pass?
    !(questions.empty? || questions.joins(:answers).empty?)
  end

  def time_in_sec	  
    time*60 if time.present?	
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def current_question_number
    if next_question || current_question
      test.questions.order(:id).where('id < ?', current_question).count + 1
    else
      test.questions.count
    end
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)
    self.success_passed = true if success?
    save!
  end

  def success?
    score >= 85
  end

  def progress_percent
    ((current_question_number.to_f - 1) / total_questions * 100).round
  end

   def total_questions
    test.questions.size
  end

  def score
    (correct_question.to_f * 100 / test.questions.count).round
  end

  def completed?
    current_question.nil?
  end

  def time_up?
    time_left.negative?
  end

  def time_left
    test.time_in_sec - (Time.current - created_at)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort unless answer_ids.nil?
  end

  def correct_answers
    current_question.answers.where(correct: true)
  end

def next_question
     test.questions.order(:id).where('id > ?', current_question.id).first
end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
belongs_to :user 
belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
  		   :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable
	
has_many   :test_passages
has_many   :tests, through: :test_passages	
has_many :authored_tests, class_name: 'Test', foreign_key: :user_id
has_many :user_badges
has_many :badges, through: :user_badges

validates :email, presence:        true, 
				  uniqueness:      true,
				  format:          { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

	def test_passage(test)
		test_passages.order(id: :desc).find_by(test_id: test.id)
	end

  def admin?
    self.is_a?(Admin)
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
	belongs_to :badge
	belongs_to :user
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_test, only: %i[start]
	
	rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

	def index
		@tests = Test.all
	end

	def start
	    current_user.tests.push(@test)
	    redirect_to current_user.test_passage(@test)
	end

	private

	def find_test
		@test = Test.find(params[:id])
	end

	def rescue_with_test_not_found
		render plain: 'Test was not found'
	end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

   COLORS = {
    success: "success",
    error: "danger",
    warning: "warning",
    info: "info"
  }

	def current_year
    "#{Time.current.year.to_i}"
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end


  def flash_message(flag)
    tag.p(flash[flag], class: "flash #{flag}") if flash[flag]
    tag.span(flash[flag]) if flash[flag]
  end

  def bootstrap_color(flag)
    "alert-#{COLORS[flag.to_sym]}"
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gists_helper.rb
module GistsHelper

  def link_to_gist(gist)
    gist_url = "https://gist.github.com/#{gist.gist_url}.git"
    link_to(gist.gist_url, gist_url, target: '_blank', rel: 'noopener')
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
def question_header(question)
    if question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

	TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze
	
	def test_level(test)
		TEST_LEVELS[test.level] || :hero
	end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <%= render 'shared/nav' %>
        <%= render 'shared/flash' %>
        
        <%= yield %>
 
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>

    <%= render 'shared/nav'%>

     <div class="container">

     <%= render 'shared/flash' %>
    <%= yield %>
       <%= render partial: 'shared/footer' %>
   </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
    <div>
       <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do %>
      <h2><%= t('.header', count: resource.errors.count) %>:
        
      </h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  <% end %>
  

app/views/shared/_flash.html.erb
<% flash.each do |flag, message| %>
 <%= tag.div class: ["alert", bootstrap_color(flag), "alert-dismissible", "fade", "show"], role: "alert" do  %>
    <%= flash_message(flag)%>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%end%>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<br><hr>
<%= github_url('ingarondel', 'TestGuru') %>
<%= link_to '', 'https://thinknetica.com', target: '_blank' %>
<p>Author: Inga</p>
<p> &copy;<%= current_year %></p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
	<% if user_signed_in? %>
	<% if current_user.admin? %>
	<%= link_to "TestGuru Admin Panel", admin_tests_path, class: 'navbar-brand' %>
	<% else %>
	<%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
	<% end %>
	<span class="navbar-text">
	    Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    	<%= button_to 'Sign Out', destroy_user_session_path, class: "btn btn-link", method: :delete %>
  	<% else %>
    	<%= link_to 'login', new_user_session_path %> |
   		<%= link_to 'Sign up', new_user_registration_path %>
 	 <% end %>

	</span>
</nav>